{"uid":"c99c823e6f7b0502","name":"User is not allowed to enter invalid phone number","fullName":"tests.test_login.TestLogin#test_invalid_phone_number","historyId":"94f93c0710e43c69cf3d1609e68099c8","time":{"start":1684827345780,"stop":1684827347627,"duration":1847},"description":"User is not allowed to enter invalid phone number","descriptionHtml":"<p>User is not allowed to enter invalid phone number</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":4,"retriesStatusChange":true,"beforeStages":[{"name":"setup","time":{"start":1684827343551,"stop":1684827345779,"duration":2228},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"User is not allowed to enter invalid phone number","status":"passed","steps":[{"name":"User clicks login icon in nav bar","time":{"start":1684827345780,"stop":1684827346213,"duration":433},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Fill phone number","time":{"start":1684827346213,"stop":1684827347142,"duration":929},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"phone_number","value":"'11111111111'"}],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},{"name":"User clicks start exploring","time":{"start":1684827347142,"stop":1684827347501,"duration":359},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[{"uid":"1c6b336d196aaff1","name":"stdout","source":"1c6b336d196aaff1.txt","type":"text/plain","size":108}],"parameters":[],"stepsCount":3,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[{"name":"setup::0","time":{"start":1684827347627,"stop":1684827347843,"duration":216},"status":"passed","steps":[],"attachments":[{"uid":"350937c54730d225","name":"Screenshot","source":"350937c54730d225.png","type":"image/png","size":124684}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true}],"labels":[{"name":"tag","value":"chrome"},{"name":"story","value":"Login functionality"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"c84a2fb0e6ff"},{"name":"thread","value":"15-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser","value":"'chrome'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"ada0b7c3f912cb7","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message:","time":{"start":1684827307110,"stop":1684827342878,"duration":35768}},{"uid":"89405d147d18f6c9","status":"passed","time":{"start":1684826886020,"stop":1684826888590,"duration":2570}},{"uid":"6b56763f34bd8a37","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb68ebe90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614050,"stop":1684826614050,"duration":0}},{"uid":"4f5a05beb284c2aa","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7bd75cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531275,"stop":1684826531275,"duration":0}}],"categories":[],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":2,"unknown":0,"total":4},"items":[{"uid":"5c78b5c0618a2c4e","reportUrl":"../5/index.html#testresult/5c78b5c0618a2c4e","status":"passed","time":{"start":1684826886020,"stop":1684826888590,"duration":2570}},{"uid":"397921096c8d5b8b","reportUrl":"../4/index.html#testresult/397921096c8d5b8b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb68ebe90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614050,"stop":1684826614050,"duration":0}},{"uid":"bae256c4470baaa5","reportUrl":"../3/index.html#testresult/bae256c4470baaa5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7bd75cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531275,"stop":1684826531275,"duration":0}}]},"tags":["chrome","@pytest.mark.usefixtures('setup')"]},"source":"c99c823e6f7b0502.json","parameterValues":["'chrome'"]}