{"uid":"ae9cc6cdef607cd0","name":"User is not allowed to enter alpha characters","fullName":"tests.test_login.TestLogin#test_invalid_input_number","historyId":"2134688c9ef20ecac430c10444678427","time":{"start":1684827270111,"stop":1684827272215,"duration":2104},"description":"User is not allowed to enter alpha characters","descriptionHtml":"<p>User is not allowed to enter alpha characters</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":3,"retriesStatusChange":true,"beforeStages":[{"name":"setup","time":{"start":1684827255780,"stop":1684827270103,"duration":14323},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"User is not allowed to enter alpha characters","status":"passed","steps":[{"name":"User clicks login icon in nav bar","time":{"start":1684827270112,"stop":1684827271233,"duration":1121},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Fill phone number","time":{"start":1684827271233,"stop":1684827271857,"duration":624},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"phone_number","value":"'aaaa'"}],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[{"uid":"c35b6bbd0dc5bd48","name":"stdout","source":"c35b6bbd0dc5bd48.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":2,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[{"name":"setup::0","time":{"start":1684827272216,"stop":1684827272759,"duration":543},"status":"passed","steps":[],"attachments":[{"uid":"280197fe20cf135f","name":"Screenshot","source":"280197fe20cf135f.png","type":"image/png","size":123946}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true}],"labels":[{"name":"tag","value":"chrome"},{"name":"story","value":"Login functionality"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"c84a2fb0e6ff"},{"name":"thread","value":"18-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser","value":"'chrome'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"daaf3f2a8f98a928","status":"passed","time":{"start":1684826921705,"stop":1684826934551,"duration":12846}},{"uid":"95e977d01cc316e9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa89abcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614050,"stop":1684826614050,"duration":0}},{"uid":"4fefb753003c32de","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff91be2290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531272,"stop":1684826531272,"duration":0}}],"categories":[],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":2,"unknown":0,"total":4},"items":[{"uid":"d91267db2c277af8","reportUrl":"../5/index.html#testresult/d91267db2c277af8","status":"passed","time":{"start":1684826921705,"stop":1684826934551,"duration":12846}},{"uid":"f040e2f2341c5e8d","reportUrl":"../4/index.html#testresult/f040e2f2341c5e8d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa89abcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614050,"stop":1684826614050,"duration":0}},{"uid":"8b39e24d4af6846d","reportUrl":"../3/index.html#testresult/8b39e24d4af6846d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff91be2290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531272,"stop":1684826531272,"duration":0}}]},"tags":["chrome","@pytest.mark.usefixtures('setup')"]},"source":"ae9cc6cdef607cd0.json","parameterValues":["'chrome'"]}