{"uid":"b3fbc754fce5ab51","name":"User is not allowed to enter alpha characters","fullName":"tests.test_login.TestLogin#test_invalid_input_number","historyId":"86204b0d5df43d727e4b2a0dade23e08","time":{"start":1684827285729,"stop":1684827287379,"duration":1650},"description":"User is not allowed to enter alpha characters","descriptionHtml":"<p>User is not allowed to enter alpha characters</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":3,"retriesStatusChange":true,"beforeStages":[{"name":"setup","time":{"start":1684827255766,"stop":1684827285725,"duration":29959},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"User is not allowed to enter alpha characters","status":"passed","steps":[{"name":"User clicks login icon in nav bar","time":{"start":1684827285730,"stop":1684827286407,"duration":677},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Fill phone number","time":{"start":1684827286407,"stop":1684827287213,"duration":806},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"phone_number","value":"'aaaa'"}],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[{"uid":"86d77c2fde27efaf","name":"stdout","source":"86d77c2fde27efaf.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":2,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[{"name":"setup::0","time":{"start":1684827287379,"stop":1684827288349,"duration":970},"status":"passed","steps":[],"attachments":[{"uid":"22022ed86278e00f","name":"Screenshot","source":"22022ed86278e00f.png","type":"image/png","size":182340}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true}],"labels":[{"name":"tag","value":"firefox"},{"name":"story","value":"Login functionality"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"c84a2fb0e6ff"},{"name":"thread","value":"23-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser","value":"'firefox'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"7b5ea5f36dae5ff7","status":"passed","time":{"start":1684826901452,"stop":1684826903837,"duration":2385}},{"uid":"8363ebfa52863b29","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff89b9bd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614051,"stop":1684826614051,"duration":0}},{"uid":"c9ae89e58f3e0056","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7f23ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531276,"stop":1684826531276,"duration":0}}],"categories":[],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":2,"unknown":0,"total":4},"items":[{"uid":"92ad3281713880d9","reportUrl":"../5/index.html#testresult/92ad3281713880d9","status":"passed","time":{"start":1684826901452,"stop":1684826903837,"duration":2385}},{"uid":"3466d084f7378e2c","reportUrl":"../4/index.html#testresult/3466d084f7378e2c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff89b9bd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614051,"stop":1684826614051,"duration":0}},{"uid":"daaf7e82af56579e","reportUrl":"../3/index.html#testresult/daaf7e82af56579e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7f23ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531276,"stop":1684826531276,"duration":0}}]},"tags":["firefox","@pytest.mark.usefixtures('setup')"]},"source":"b3fbc754fce5ab51.json","parameterValues":["'firefox'"]}