{"uid":"27b42c8df3968fb7","name":"User is able to login,this should fail","fullName":"tests.test_login.TestLogin#test_user_login","historyId":"39cff70f68670e41090de5b2f95773fe","time":{"start":1684826886851,"stop":1684826933592,"duration":46741},"description":"User is able to login","descriptionHtml":"<p>User is able to login</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0xaaaacefd679c <unknown>\n#1 0xaaaaced4b3cc <unknown>\n#2 0xaaaaced7f0e0 <unknown>\n#3 0xaaaacedb3d2c <unknown>\n#4 0xaaaaced7547c <unknown>\n#5 0xaaaaced76894 <unknown>\n#6 0xaaaacefa4a7c <unknown>\n#7 0xaaaacefa700c <unknown>\n#8 0xaaaacefa6bac <unknown>\n#9 0xaaaacefad4d8 <unknown>\n#10 0xaaaacefa7924 <unknown>\n#11 0xaaaacef86e20 <unknown>\n#12 0xaaaacefc0eec <unknown>\n#13 0xaaaacefc10b8 <unknown>\n#14 0xaaaacefcf170 <unknown>\n#15 0xffffa240edd8 <unknown>\n#16 0xffffa2477e5c <unknown>","statusTrace":"self = <tests.test_login.TestLogin object at 0xffff97b67950>\n\n>   ???\n\n/Users/alya/Documents/selenium-ci-cd/tests/test_login.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/login_page.py:56: in login_existing_user\n    assert self.get_user_name() == \"Hi, \"+username\npages/nav_bar_page.py:25: in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\npages/base_page.py:33: in get_text\n    element: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"176434d98e046253ca4e8bfdfcc2de0b\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0xffff97b80b80>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0xaaaacefd679c <unknown>\nE       #1 0xaaaaced4b3cc <unknown>\nE       #2 0xaaaaced7f0e0 <unknown>\nE       #3 0xaaaacedb3d2c <unknown>\nE       #4 0xaaaaced7547c <unknown>\nE       #5 0xaaaaced76894 <unknown>\nE       #6 0xaaaacefa4a7c <unknown>\nE       #7 0xaaaacefa700c <unknown>\nE       #8 0xaaaacefa6bac <unknown>\nE       #9 0xaaaacefad4d8 <unknown>\nE       #10 0xaaaacefa7924 <unknown>\nE       #11 0xaaaacef86e20 <unknown>\nE       #12 0xaaaacefc0eec <unknown>\nE       #13 0xaaaacefc10b8 <unknown>\nE       #14 0xaaaacefcf170 <unknown>\nE       #15 0xffffa240edd8 <unknown>\nE       #16 0xffffa2477e5c <unknown>\n\n/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":2,"retriesStatusChange":false,"beforeStages":[{"name":"setup","time":{"start":1684826874791,"stop":1684826886846,"duration":12055},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"User is able to login","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0xaaaacefd679c <unknown>\n#1 0xaaaaced4b3cc <unknown>\n#2 0xaaaaced7f0e0 <unknown>\n#3 0xaaaacedb3d2c <unknown>\n#4 0xaaaaced7547c <unknown>\n#5 0xaaaaced76894 <unknown>\n#6 0xaaaacefa4a7c <unknown>\n#7 0xaaaacefa700c <unknown>\n#8 0xaaaacefa6bac <unknown>\n#9 0xaaaacefad4d8 <unknown>\n#10 0xaaaacefa7924 <unknown>\n#11 0xaaaacef86e20 <unknown>\n#12 0xaaaacefc0eec <unknown>\n#13 0xaaaacefc10b8 <unknown>\n#14 0xaaaacefcf170 <unknown>\n#15 0xffffa240edd8 <unknown>\n#16 0xffffa2477e5c <unknown>","statusTrace":"self = <tests.test_login.TestLogin object at 0xffff97b67950>\n\n>   ???\n\n/Users/alya/Documents/selenium-ci-cd/tests/test_login.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/login_page.py:56: in login_existing_user\n    assert self.get_user_name() == \"Hi, \"+username\npages/nav_bar_page.py:25: in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\npages/base_page.py:33: in get_text\n    element: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"176434d98e046253ca4e8bfdfcc2de0b\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0xffff97b80b80>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0xaaaacefd679c <unknown>\nE       #1 0xaaaaced4b3cc <unknown>\nE       #2 0xaaaaced7f0e0 <unknown>\nE       #3 0xaaaacedb3d2c <unknown>\nE       #4 0xaaaaced7547c <unknown>\nE       #5 0xaaaaced76894 <unknown>\nE       #6 0xaaaacefa4a7c <unknown>\nE       #7 0xaaaacefa700c <unknown>\nE       #8 0xaaaacefa6bac <unknown>\nE       #9 0xaaaacefad4d8 <unknown>\nE       #10 0xaaaacefa7924 <unknown>\nE       #11 0xaaaacef86e20 <unknown>\nE       #12 0xaaaacefc0eec <unknown>\nE       #13 0xaaaacefc10b8 <unknown>\nE       #14 0xaaaacefcf170 <unknown>\nE       #15 0xffffa240edd8 <unknown>\nE       #16 0xffffa2477e5c <unknown>\n\n/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException","steps":[{"name":"User logs in","time":{"start":1684826886852,"stop":1684826933590,"duration":46738},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0xaaaacefd679c <unknown>\n#1 0xaaaaced4b3cc <unknown>\n#2 0xaaaaced7f0e0 <unknown>\n#3 0xaaaacedb3d2c <unknown>\n#4 0xaaaaced7547c <unknown>\n#5 0xaaaaced76894 <unknown>\n#6 0xaaaacefa4a7c <unknown>\n#7 0xaaaacefa700c <unknown>\n#8 0xaaaacefa6bac <unknown>\n#9 0xaaaacefad4d8 <unknown>\n#10 0xaaaacefa7924 <unknown>\n#11 0xaaaacef86e20 <unknown>\n#12 0xaaaacefc0eec <unknown>\n#13 0xaaaacefc10b8 <unknown>\n#14 0xaaaacefcf170 <unknown>\n#15 0xffffa240edd8 <unknown>\n#16 0xffffa2477e5c <unknown>\n\n","statusTrace":"  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/login_page.py\", line 56, in login_existing_user\n    assert self.get_user_name() == \"Hi, \"+username\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/nav_bar_page.py\", line 25, in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/base_page.py\", line 33, in get_text\n    element: WebElement = self.wait.until(\n                          ^^^^^^^^^^^^^^^^\n  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[{"name":"User clicks login icon in nav bar","time":{"start":1684826886852,"stop":1684826889278,"duration":2426},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Fill phone number","time":{"start":1684826889278,"stop":1684826891703,"duration":2425},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"phone_number","value":"'01116888790'"}],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},{"name":"User clicks start exploring","time":{"start":1684826891704,"stop":1684826897403,"duration":5699},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"User fill password","time":{"start":1684826897404,"stop":1684826901438,"duration":4034},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"password","value":"'test'"}],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},{"name":"User clicks login button","time":{"start":1684826901438,"stop":1684826901916,"duration":478},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Return username when user logged in","time":{"start":1684826901916,"stop":1684826933588,"duration":31672},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0xaaaacefd679c <unknown>\n#1 0xaaaaced4b3cc <unknown>\n#2 0xaaaaced7f0e0 <unknown>\n#3 0xaaaacedb3d2c <unknown>\n#4 0xaaaaced7547c <unknown>\n#5 0xaaaaced76894 <unknown>\n#6 0xaaaacefa4a7c <unknown>\n#7 0xaaaacefa700c <unknown>\n#8 0xaaaacefa6bac <unknown>\n#9 0xaaaacefad4d8 <unknown>\n#10 0xaaaacefa7924 <unknown>\n#11 0xaaaacef86e20 <unknown>\n#12 0xaaaacefc0eec <unknown>\n#13 0xaaaacefc10b8 <unknown>\n#14 0xaaaacefcf170 <unknown>\n#15 0xffffa240edd8 <unknown>\n#16 0xffffa2477e5c <unknown>\n\n","statusTrace":"  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/nav_bar_page.py\", line 25, in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/base_page.py\", line 33, in get_text\n    element: WebElement = self.wait.until(\n                          ^^^^^^^^^^^^^^^^\n  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[],"parameters":[{"name":"phone_number","value":"'01116888790'"},{"name":"password","value":"'test'"},{"name":"username","value":"'alyaothman'"}],"stepsCount":6,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[{"uid":"8389adc9aaa1057b","name":"stdout","source":"8389adc9aaa1057b.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":7,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"setup::0","time":{"start":1684826933641,"stop":1684826934076,"duration":435},"status":"passed","steps":[],"attachments":[{"uid":"69dad88f541b8848","name":"Screenshot","source":"69dad88f541b8848.png","type":"image/png","size":109070}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true}],"labels":[{"name":"tag","value":"chrome"},{"name":"story","value":"Login functionality"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"e7a5f6497e16"},{"name":"thread","value":"27-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser","value":"'chrome'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"a947956fc4aebd38","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff998e4150>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614052,"stop":1684826614052,"duration":0}},{"uid":"d008620681a368b0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7ebae210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531275,"stop":1684826531275,"duration":0}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"3340757861709241","reportUrl":"../4/index.html#testresult/3340757861709241","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff998e4150>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614052,"stop":1684826614052,"duration":0}},{"uid":"b8bd5bd1039e3070","reportUrl":"../3/index.html#testresult/b8bd5bd1039e3070","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7ebae210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531275,"stop":1684826531275,"duration":0}}]},"tags":["chrome","@pytest.mark.usefixtures('setup')"]},"source":"27b42c8df3968fb7.json","parameterValues":["'chrome'"]}