{"86204b0d5df43d727e4b2a0dade23e08":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"3466d084f7378e2c","reportUrl":"../4/index.html#testresult/3466d084f7378e2c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff89b9bd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614051,"stop":1684826614051,"duration":0}},{"uid":"daaf7e82af56579e","reportUrl":"../3/index.html#testresult/daaf7e82af56579e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7f23ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531276,"stop":1684826531276,"duration":0}}]},"2134688c9ef20ecac430c10444678427":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"f040e2f2341c5e8d","reportUrl":"../4/index.html#testresult/f040e2f2341c5e8d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa89abcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614050,"stop":1684826614050,"duration":0}},{"uid":"8b39e24d4af6846d","reportUrl":"../3/index.html#testresult/8b39e24d4af6846d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff91be2290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531272,"stop":1684826531272,"duration":0}}]},"c70b764e14c198ae23bb359c5cb1e46d":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"d7b9bb25454da721","reportUrl":"../4/index.html#testresult/d7b9bb25454da721","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x0000000100967598 chromedriver + 4973976\n1   chromedriver                        0x000000010095e913 chromedriver + 4938003\n2   chromedriver                        0x000000010051bcd6 chromedriver + 470230\n3   chromedriver                        0x000000010055f2ff chromedriver + 746239\n4   chromedriver                        0x000000010055f591 chromedriver + 746897\n5   chromedriver                        0x00000001005a1384 chromedriver + 1016708\n6   chromedriver                        0x00000001005839ed chromedriver + 895469\n7   chromedriver                        0x000000010059e856 chromedriver + 1005654\n8   chromedriver                        0x0000000100583793 chromedriver + 894867\n9   chromedriver                        0x000000010055121f chromedriver + 688671\n10  chromedriver                        0x000000010055256e chromedriver + 693614\n11  chromedriver                        0x0000000100921bb7 chromedriver + 4688823\n12  chromedriver                        0x0000000100926a51 chromedriver + 4708945\n13  chromedriver                        0x000000010092d40f chromedriver + 4736015\n14  chromedriver                        0x000000010092791a chromedriver + 4712730\n15  chromedriver                        0x00000001008fa87c chromedriver + 4528252\n16  chromedriver                        0x0000000100946f28 chromedriver + 4841256\n17  chromedriver                        0x00000001009470a7 chromedriver + 4841639\n18  chromedriver                        0x000000010095828f chromedriver + 4911759\n19  libsystem_pthread.dylib             0x00007fff204068fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff20402443 thread_start + 15","time":{"start":1684825090955,"stop":1684825133127,"duration":42172}},{"uid":"e68d66859d770ad7","reportUrl":"../3/index.html#testresult/e68d66859d770ad7","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x0000000100967598 chromedriver + 4973976\n1   chromedriver                        0x000000010095e913 chromedriver + 4938003\n2   chromedriver                        0x000000010051bcd6 chromedriver + 470230\n3   chromedriver                        0x000000010055f2ff chromedriver + 746239\n4   chromedriver                        0x000000010055f591 chromedriver + 746897\n5   chromedriver                        0x00000001005a1384 chromedriver + 1016708\n6   chromedriver                        0x00000001005839ed chromedriver + 895469\n7   chromedriver                        0x000000010059e856 chromedriver + 1005654\n8   chromedriver                        0x0000000100583793 chromedriver + 894867\n9   chromedriver                        0x000000010055121f chromedriver + 688671\n10  chromedriver                        0x000000010055256e chromedriver + 693614\n11  chromedriver                        0x0000000100921bb7 chromedriver + 4688823\n12  chromedriver                        0x0000000100926a51 chromedriver + 4708945\n13  chromedriver                        0x000000010092d40f chromedriver + 4736015\n14  chromedriver                        0x000000010092791a chromedriver + 4712730\n15  chromedriver                        0x00000001008fa87c chromedriver + 4528252\n16  chromedriver                        0x0000000100946f28 chromedriver + 4841256\n17  chromedriver                        0x00000001009470a7 chromedriver + 4841639\n18  chromedriver                        0x000000010095828f chromedriver + 4911759\n19  libsystem_pthread.dylib             0x00007fff204068fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff20402443 thread_start + 15","time":{"start":1684825090955,"stop":1684825133127,"duration":42172}},{"uid":"c9151328cf7d7c91","reportUrl":"../2/index.html#testresult/c9151328cf7d7c91","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x0000000100967598 chromedriver + 4973976\n1   chromedriver                        0x000000010095e913 chromedriver + 4938003\n2   chromedriver                        0x000000010051bcd6 chromedriver + 470230\n3   chromedriver                        0x000000010055f2ff chromedriver + 746239\n4   chromedriver                        0x000000010055f591 chromedriver + 746897\n5   chromedriver                        0x00000001005a1384 chromedriver + 1016708\n6   chromedriver                        0x00000001005839ed chromedriver + 895469\n7   chromedriver                        0x000000010059e856 chromedriver + 1005654\n8   chromedriver                        0x0000000100583793 chromedriver + 894867\n9   chromedriver                        0x000000010055121f chromedriver + 688671\n10  chromedriver                        0x000000010055256e chromedriver + 693614\n11  chromedriver                        0x0000000100921bb7 chromedriver + 4688823\n12  chromedriver                        0x0000000100926a51 chromedriver + 4708945\n13  chromedriver                        0x000000010092d40f chromedriver + 4736015\n14  chromedriver                        0x000000010092791a chromedriver + 4712730\n15  chromedriver                        0x00000001008fa87c chromedriver + 4528252\n16  chromedriver                        0x0000000100946f28 chromedriver + 4841256\n17  chromedriver                        0x00000001009470a7 chromedriver + 4841639\n18  chromedriver                        0x000000010095828f chromedriver + 4911759\n19  libsystem_pthread.dylib             0x00007fff204068fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff20402443 thread_start + 15","time":{"start":1684825090955,"stop":1684825133127,"duration":42172}}]},"39cff70f68670e41090de5b2f95773fe":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"3340757861709241","reportUrl":"../4/index.html#testresult/3340757861709241","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff998e4150>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614052,"stop":1684826614052,"duration":0}},{"uid":"b8bd5bd1039e3070","reportUrl":"../3/index.html#testresult/b8bd5bd1039e3070","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7ebae210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531275,"stop":1684826531275,"duration":0}}]},"d4789fa5b9353700b289a8b501933add":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":1,"unknown":0,"total":2},"items":[{"uid":"47cc474944e860c5","reportUrl":"../4/index.html#testresult/47cc474944e860c5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb628b590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614677,"stop":1684826614677,"duration":0}},{"uid":"35d59993de6a1d69","reportUrl":"../3/index.html#testresult/35d59993de6a1d69","status":"passed","time":{"start":1684826537798,"stop":1684826539823,"duration":2025}}]},"a8241406a7d72ac646d6a48aaecfd220":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"4536443c46cdac97","reportUrl":"../4/index.html#testresult/4536443c46cdac97","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff891a7a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614049,"stop":1684826614049,"duration":0}},{"uid":"340d82bf29c6403f","reportUrl":"../3/index.html#testresult/340d82bf29c6403f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffacfe5e10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531272,"stop":1684826531272,"duration":0}}]},"117e0363055ab3ace5ba15d45154e621":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":1,"unknown":0,"total":2},"items":[{"uid":"ddba4939fe5e4a1d","reportUrl":"../4/index.html#testresult/ddba4939fe5e4a1d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff88b47210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614445,"stop":1684826614445,"duration":0}},{"uid":"72939243637fc739","reportUrl":"../3/index.html#testresult/72939243637fc739","status":"passed","time":{"start":1684826540432,"stop":1684826542287,"duration":1855}}]},"3b0c87cbb1d3e9ab8f5076c7a763fb5c":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"9d52666f86115bed","reportUrl":"../4/index.html#testresult/9d52666f86115bed","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7ccdbc90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614087,"stop":1684826614087,"duration":0}},{"uid":"75ec73be64fef1d2","reportUrl":"../3/index.html#testresult/75ec73be64fef1d2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa9eae190>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531281,"stop":1684826531281,"duration":0}}]},"94f93c0710e43c69cf3d1609e68099c8":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"397921096c8d5b8b","reportUrl":"../4/index.html#testresult/397921096c8d5b8b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb68ebe90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614050,"stop":1684826614050,"duration":0}},{"uid":"bae256c4470baaa5","reportUrl":"../3/index.html#testresult/bae256c4470baaa5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7bd75cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531275,"stop":1684826531275,"duration":0}}]},"88abe5aa9c6c37e78b845a216ec154ba":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"a6e27f000ae1f5e1","reportUrl":"../4/index.html#testresult/a6e27f000ae1f5e1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7d9ef9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614083,"stop":1684826614083,"duration":0}},{"uid":"db70a8e855bca114","reportUrl":"../3/index.html#testresult/db70a8e855bca114","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffab67a190>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531273,"stop":1684826531273,"duration":0}}]},"771241e1613829427ee34fac13caebc2":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"edefa6f04fb11bfc","reportUrl":"../4/index.html#testresult/edefa6f04fb11bfc","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffaa577b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614082,"stop":1684826614082,"duration":0}},{"uid":"1a41b62e600cd598","reportUrl":"../3/index.html#testresult/1a41b62e600cd598","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb8705dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531278,"stop":1684826531278,"duration":0}}]}}